# https://numtide.github.io/devshell
[devshell]
packages = [
         "cargo",
         "clippy",
         "lldb_9",
         "llvmPackages_9.clangUseLLVM",
         "nodejs",  # for dap-mode debugger (confirm later whether it really is)
         "rust-analyzer",
         "rustc",
         "rustfmt"
]

[[commands]]
package = "devshell.cli"
help = "Per project developer environments"
