# https://numtide.github.io/devshell
[devshell]
packages = [
         "cargo",
         "llvmPackages.clangUseLLVM",
         "clippy",
         "rust-analyzer",
         "rustc",
         "rustfmt"
]

[[commands]]
package = "devshell.cli"
help = "Per project developer environments"
