# https://numtide.github.io/devshell
[devshell]
packages = [
         "cargo",
         "clippy",
         "gcc",
         "gdb",
         "rust-analyzer",
         "rustc",
         "rustfmt",
         "vscode-extensions.ms-vscode.cpptools",
]

[[commands]]
package = "devshell.cli"
help = "Per project developer environments"
